/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LuxuryFashionTracking } from "./LuxuryFashionTracking";
export type { Supplychain } from "./Supplychain";
