/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SupplychainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addManufacturingStage"
      | "completeManufacturingStage"
      | "createProduct"
      | "getHistory"
      | "productCount"
      | "products"
      | "sellProduct"
      | "startManufacturingStage"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addManufacturingStage",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "completeManufacturingStage",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createProduct",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "productCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "products",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellProduct",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "startManufacturingStage",
    values: [BigNumberish, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addManufacturingStage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeManufacturingStage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHistory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startManufacturingStage",
    data: BytesLike
  ): Result;
}

export interface Supplychain extends BaseContract {
  connect(runner?: ContractRunner | null): Supplychain;
  waitForDeployment(): Promise<this>;

  interface: SupplychainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addManufacturingStage: TypedContractMethod<
    [_productId: BigNumberish, stageName: string, _timestamp: string],
    [void],
    "nonpayable"
  >;

  completeManufacturingStage: TypedContractMethod<
    [_productId: BigNumberish, stageIndex: BigNumberish, _timestamp: string],
    [void],
    "nonpayable"
  >;

  createProduct: TypedContractMethod<
    [_description: string, _timestamp: string],
    [bigint],
    "nonpayable"
  >;

  getHistory: TypedContractMethod<
    [_productId: BigNumberish],
    [[string[], string[]]],
    "view"
  >;

  productCount: TypedContractMethod<[], [bigint], "view">;

  products: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, string] & { description: string; owner: string }],
    "view"
  >;

  sellProduct: TypedContractMethod<
    [_productId: BigNumberish, _newOwner: AddressLike, _timestamp: string],
    [void],
    "nonpayable"
  >;

  startManufacturingStage: TypedContractMethod<
    [_productId: BigNumberish, stageIndex: BigNumberish, _timestamp: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addManufacturingStage"
  ): TypedContractMethod<
    [_productId: BigNumberish, stageName: string, _timestamp: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completeManufacturingStage"
  ): TypedContractMethod<
    [_productId: BigNumberish, stageIndex: BigNumberish, _timestamp: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProduct"
  ): TypedContractMethod<
    [_description: string, _timestamp: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getHistory"
  ): TypedContractMethod<
    [_productId: BigNumberish],
    [[string[], string[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "productCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, string] & { description: string; owner: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "sellProduct"
  ): TypedContractMethod<
    [_productId: BigNumberish, _newOwner: AddressLike, _timestamp: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startManufacturingStage"
  ): TypedContractMethod<
    [_productId: BigNumberish, stageIndex: BigNumberish, _timestamp: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
